version: '3'

services:

  web-server:
    build:
      context: ./web
    ports:
      - 80:6000 
    env_file:
      ./credentials.env
    volumes:
      - ./web/src:/app
    container_name: agile-web

  db-server:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306 
    volumes:
      - ./db:/var/lib/mysql 
    container_name: agile-db

volumes:
  db:
